import queue  # Import the thread-safe queue module
import threading
import webbrowser
from base64 import b64encode
from datetime import datetime, timedelta
from typing import Annotated, Any

import flask
import httpx
from pydantic import AfterValidator, BaseModel
from werkzeug.serving import make_server  # For graceful server shutdown

from src import classes
import json

# --- Configuration ---

# Global objects for communication
app = flask.Flask("spotify_auth_app")
auth_queue = queue.Queue()
server_shutdown = threading.Event()  # A flag to signal when the server is ready to stop
server_instance = None  # To hold the server object for shutdown


def validate_spot_api(s: str) -> str:
    if "https://api.spotify.com" not in s:
        raise ValueError(f"Url is {s} which does not contain https://api.spotify.com")
    return s


# --- Flask Server Routes ---
@app.route("/")
def base():
    return "<h1>Spotify Auth Setup</h1><p>Waiting for redirect...</p>"


@app.route("/callback")
def callback():
    """Captures the authorization code and signals the main thread."""
    global server_instance

    auth_code = flask.request.args.get("code")

    if auth_code:
        # 1. Put the captured code into the queue for the main thread
        auth_queue.put(auth_code)

        # 2. Signal the server to stop gracefully
        if server_instance:
            server_shutdown.set()

        return "<h1>Auth Complete!</h1><p>You can close this window.</p>"

    return "<h1>Error</h1><p>No code received.</p>", 400


# --- Server Threading Class ---
class ServerThread(threading.Thread):
    """Runs the Flask server in a background thread."""

    def __init__(self, app):
        super().__init__()
        # Use make_server for controlled shutdown
        self.server = make_server("127.0.0.1", 5000, app, threaded=True)
        self.ctx = app.app_context()
        global server_instance
        server_instance = self.server  # Store reference for access in callback

    def run(self):
        print("🌍 Starting Flask server on http://127.0.0.1:5000...")
        self.ctx.push()
        # Serve forever until shutdown() is called
        self.server.serve_forever()
        print("🌍 Flask server shut down.")


class auth_params(BaseModel):
    client_id: str
    client_secret: str
    response_type: str = "code"
    redirect_uri: str = "http://127.0.0.1:5000/callback"
    scope: str
    state: str


class spotify_auth(BaseModel):
    access_token: str
    token_type: str
    expires_in: int
    expires_at: datetime
    refresh_token: str
    scope: str


def length_check(s: str, length: int) -> str:
    if len(s) != length:
        raise ValueError(f"{s} is not a string of length {length}")
    return s


class spotify(BaseModel):
    """
    A wrapper on the spotify API.

    Attributes:
        auth_params: auth_params, contains secret etc for oauth. See spotify.auth_params
        base_url: The base url for the api. Defaults to "https://api.spotify.com/v1
        auth: Optional, a class of type spotify.spotify_auth that contains the oauth token, expiry time etc. Generated by get_auth_code_and_tokens()
    """

    auth_params: auth_params
    base_url: str = "https://api.spotify.com/v1"
    auth: spotify_auth | None = None
    user_id: str | None = None

    def _check_auth(self):
        if self.auth is None:
            raise RuntimeError("You have not authenticated")

    def _check_expired(self):
        """
        Check if auth exists and is not expired, if expired reauthenticate
        """
        self._check_auth()
        if self.auth.expires_at <= datetime.now():
            print("Auth has expired. Authenticating...")
            self.get_auth_code_and_tokens()

    def _construct_call(
        self,
        endpoint: str,
        method: str = "GET",
        params: dict[str, Any] = None,
        data: dict[str, Any] = None,
    ) -> dict[str, Any]:
        """Constructs a Spotify api call and returns the resulting json as a dict

        Args:
            params: a dictionary of params to the api call
            data: A dictionary of data if method is of POST
            endpoint: The endpoint to hit
            method: The rest method must be one of GET, POST, PUT

        Returns:
            A dict containing the result of the api call after checking for errors
        """
        self._check_expired()
        endpoint = endpoint.removeprefix("/")
        url = f"{self.base_url}/{endpoint}"
        headers = {"Authorization": f"Bearer {self.auth.access_token}"}
        response = httpx.request(method, url, headers=headers, params=params, json=data)
        response.raise_for_status()

        return response.json()

    def _paginate(self, url: Annotated[str, AfterValidator(validate_spot_api)]):
        """If there is a next url pass it to this function in a `while call["next"] is not None` statement to get the next page of results"""
        # strip the base url + '/' from next url and pass to construct call
        endpoint_w_param = url.removeprefix(self.base_url + "/")
        return self._construct_call(endpoint=endpoint_w_param, method="GET")

    def search(
        self, artist: str, album_name: str | None = None, market: str = "AU"
    ) -> list[classes.album] | list[dict[str, str]]:
        def search_type_val(s: str) -> str:
            search_types = ["album", "artist", "track"]
            if s not in search_types:
                raise ValueError(f"Search type is {s} but must be one of {search_types}")
            return s

        def id_title(i: dict[str, Any], search_type: str) -> list[classes.album] | list[dict[str, str]]:
            out = []
            for res in i[search_type + "s"]["items"]:
                if search_type == "album":
                    artists = [a["name"] for a in res["artists"]]
                    title = res["name"]
                    id = res["id"]
                    out.append(classes.album(artists=artists, title=title, id=id))
                if search_type == "artist":
                    out.append({"artist": res["name"]})
            return out

        class search_params(BaseModel):
            type: Annotated[str, AfterValidator(search_type_val)]
            q: str
            market: Annotated[str, lambda x: length_check(x, 2)]

        search_type = "artist"
        q = f"artist:{artist}"
        if album_name is not None:
            search_type = "album"
            q = f"{q} album:{album_name}"

        params = search_params(type=search_type, q=q, market=market)
        call = self._construct_call("search", method="GET", params=params.model_dump())
        results = id_title(call, search_type=search_type)
        while call[search_type + "s"]["next"] is not None:
            call = self._paginate(call[search_type + "s"]["next"])
            results.extend(id_title(call, search_type=search_type))
        return results

    def get_album_tracks(
        self,
        id: str,
        market: Annotated[str, AfterValidator(lambda x: length_check(x, 2))] = "AU",
    ) -> list[str]:
        def process_tracks(call: dict[str, Any]) -> list[str]:
            return [i["id"] for i in call["items"]]

        call = self._construct_call(endpoint=f"albums/{id}/tracks", params={"Market": market, "limit": 50})
        result = process_tracks(call)

        while call["next"] is not None:
            call = self._paginate(call["next"])
            result.extend(process_tracks(call))
        return result

    def get_tracks(
        self, ids: list[str] | str, market: Annotated[str, AfterValidator(lambda x: length_check(x, 2))] = "AU"
    ) -> list[dict[str, Any]]:
        if isinstance(ids, list):
            ids = ",".join(ids)
        call = self._construct_call(endpoint="/tracks", params={"market": market, "ids": ids, "limit": 50})
        print(call.keys())
        items = call["tracks"]

        return items

    def playlist_exist(self, id: str) -> bool:
        return "error" not in self._construct_call(f"playlists/{id}")

    def get_playlist_by_name(self, name: str):
        call = self._construct_call("me/playlists", params={"limit": 50})
        names = [i["name"] for i in call["items"]]
        if name in names:
            playlist = call["items"][names.index(name)]
            return {i: playlist[i] for i in playlist if i in ["id", "href"]}
        while call["next"] is not None:
            call = self._paginate(call["next"])
            names.extend([i["name"] for i in call["items"]])
            if name in names:
                playlist = call["items"][names.index(name)]
                return {i: playlist[i] for i in playlist if i in ["id", "href"]}

        return None

    def get_user_playlists(self) -> list[dict[str, Any]]:
        """Get all playlists for the authenticated user.

        Returns:
            List of playlist dicts with keys: id, name, href, track_count
        """
        call = self._construct_call("me/playlists", params={"limit": 50})
        playlists = []

        for item in call["items"]:
            playlists.append({
                "id": item["id"],
                "name": item["name"],
                "href": item["href"],
                "track_count": item["tracks"]["total"],
            })

        while call["next"] is not None:
            call = self._paginate(call["next"])
            for item in call["items"]:
                playlists.append({
                    "id": item["id"],
                    "name": item["name"],
                    "href": item["href"],
                    "track_count": item["tracks"]["total"],
                })

        return playlists

    def get_playlist_tracks(self, playlist_id: str) -> list[dict[str, Any]]:
        """Get all tracks from a playlist.

        Args:
            playlist_id: Spotify playlist ID

        Returns:
            List of track dicts with keys: track_id, artist, album
        """
        call = self._construct_call(f"playlists/{playlist_id}/tracks", params={"limit": 50})
        tracks = []

        for item in call["items"]:
            if item["track"] is None:
                continue
            track = item["track"]
            # Get first artist and album
            artist = track["artists"][0]["name"] if track["artists"] else "Unknown"
            album = track["album"]["name"] if track["album"] else "Unknown"

            tracks.append({
                "track_id": track["id"],
                "artist": artist,
                "album": album,
            })

        while call["next"] is not None:
            call = self._paginate(call["next"])
            for item in call["items"]:
                if item["track"] is None:
                    continue
                track = item["track"]
                artist = track["artists"][0]["name"] if track["artists"] else "Unknown"
                album = track["album"]["name"] if track["album"] else "Unknown"

                tracks.append({
                    "track_id": track["id"],
                    "artist": artist,
                    "album": album,
                })

        return tracks

    def create_playlist(self, name: str, public: bool = True, collaborative: bool = False):
        body = {"name": name, "public": public, "collaborative": collaborative, "description": ""}

        result = self._construct_call(endpoint=f"users/{self.user_id}/playlists", method="POST", data=body)
        return {i: result[i] for i in result if i in ["id", "href"]}

    def add_to_playlist(
        self,
        tracks: list[str] | list[str],
        playlist_id: str,
        position: int = 0,
    ):
        if not self.playlist_exist(playlist_id):
            raise RuntimeError(f"No playlist with id {playlist_id}")
        if not isinstance(tracks, list):
            tracks = [tracks]
        chunk_size = 99
        n_chunks = len(tracks) // chunk_size + int((len(tracks) % chunk_size) > 0)

        for ch in range(n_chunks):
            start = ch * chunk_size
            end = min(start + chunk_size, len(tracks))
            uri_str = [f"spotify:track:{t}" for t in tracks[start:end]]
            print(f"passing {len(uri_str)} uris")
            data = {"position": position, "uris": uri_str}
            print(data)
            self._construct_call(
                f"playlists/{playlist_id}/tracks",
                method="POST",
                data=data,
            )
        return True

    def get_auth_code_and_tokens(self):
        """Starts the a Flask server, gets the code, and exchanges it for tokens."""
        # 1. Start the Flask server thread
        server_thread = ServerThread(app)
        server_thread.daemon = True  # Allow the main script to exit even if the thread is running
        server_thread.start()

        # 2. Construct and open the Authorization URL

        # Use httpx to get the final authorization redirect URL (Location header)
        auth_response = httpx.get(
            "https://accounts.spotify.com/authorize",
            params=self.auth_params.model_dump(),
            follow_redirects=False,
        )
        auth_url = auth_response.headers.get("Location")

        print("\n--- SPOTIFY LOGIN REQUIRED ---")
        print(f"Opening URL in browser: {auth_url}")
        webbrowser.open(auth_url)

        # 3. Wait for the authorization code from the queue
        print("\nWaiting for authorization (check your browser)...", end="", flush=True)
        try:
            # This is the line that PAUSES execution until the 'callback' puts data in the queue
            final_auth_code = auth_queue.get(timeout=60)  # Wait up to 60 seconds
            print("\n✅ Authorization code received.")

        except queue.Empty:
            print("\n❌ Timed out waiting for authorization code.")
            return

            # 4. Exchange the Code for Access and Refresh Tokens
        print("--- EXCHANGING CODE FOR TOKENS ---")

        client_creds = f"{self.auth_params.client_id}:{self.auth_params.client_secret}"
        auth_header_value = b64encode(client_creds.encode()).decode("utf-8")

        try:
            time = datetime.now()
            expiry_time = time + timedelta(seconds=3300)  # expires in an hour but lets be conservative
            token_response = httpx.post(
                "https://accounts.spotify.com/api/token",
                data={
                    "grant_type": "authorization_code",
                    "code": final_auth_code,
                    "redirect_uri": self.auth_params.redirect_uri,
                },
                headers={
                    "Authorization": f"Basic {auth_header_value}",  # Corrected 'Authorization' spelling
                    "Content-Type": "application/x-www-form-urlencoded",
                },
            )
            token_response.raise_for_status()  # Raise for bad status codes

            token_info = token_response.json()
            token_info["expires_at"] = expiry_time

            self.auth = spotify_auth(**token_info)

            # save user id
            self.user_id = self._construct_call("me", method="GET")["id"]
        except httpx.HTTPStatusError as e:
            print(f"\n❌ Token exchange failed: Status {e.response.status_code}")
            print(f"Response Body: {e.response.text}")
            raise


if __name__ == "__main__":
    from src.config import load_config

    config = load_config()
    a = auth_params(
        client_id=config.spotify.client_id,
        client_secret=config.spotify.client_secret,
        scope=config.spotify.scopes,
        state="state",
    )

    spot_client = spotify(auth_params=a)
    spot_client.get_auth_code_and_tokens()
    print(spot_client.search("Steely Dan", "Aja"))
